name: build-and-run-tests
run-name: ${{ github.actor }} is building and running tests
on: [pull_request]
jobs:
  build-and-test-app:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install deps
        run: npm ci
      - run: npm run build --if-present
      - run: npm run test
